# Power Monitor Configuration
DEVICE_ID=powermon_100000008d8d6dc5
LOCATION_NAME=Rockhill
CT_RATING=30
GRID_VOLTAGE=120.0
SERVER_URL=https://linesights.com/api/data
DETECTED_TIMEZONE=America/New_York
SEND_INTERVAL=1
